### ISSUE TITLE
When search by geolocation, would like to have this format [ geocolocation=latitude,longitude]

### ISSUE THREAD

**Issue by TorIsHere** [gobbl/snakebite#26]
For your consideration

**Comment by kelvintaywl** [comment]
@TorIsHere i have a local branch where i worked on this. 

I thought it might only take 20 mins to fix this with all the tests but there's a lot of areas involved. For instance, by switching to this method, it makes sense that in the response,the geolocation value in each restaurant payload should also be `[latitude, longitude]` too right?

Took me > 1 hour changing all these, as well as the code. Couldn't fix one of the tests as it seem rather 
めんどくさい . Maybe I'm tired, I guess I will take a closer look at this hopefully before Friday.

**Comment by kelvintaywl** [comment]
a workaround could be that instead of specifying the `geolocation` query argument, we switch it to `lon` and `lat` instead so the server just catches by the keys.

benefits:
- everyone is happy; no confusion over any conventions
- grabbing by two distinct keys makes backend logic slightly easier, instead of always reversing order so that MongoDB understands

cons:
- url might become too long, especially if we explicitly use `longitude` and `latitude` as query arguments
- away from geolocation convention? (if there was any?) Google uses the format `@lat,lon`

**Comment by TorIsHere** [comment]
I like the idea of separating to `lat` and `lon`

**Comment by TorIsHere** [comment]
I think Google's convention is 
```
"location" : {
   "lat" : 37.42291810,
  "lng" : -122.08542120
 },
```
https://developers.google.com/maps/documentation/geocoding/#JSON

**Comment by TorIsHere** [comment]
"geolocation":  "lon", "lat" " お願いします

**Comment by TorIsHere** [comment]
I checked on the client side, it works fine. Thanks.

**Comment by kelvintaywl** [comment]
:+1:
